### PR TITLE
fix: prevent opaque prop suggestion in IDEs

### PR DESCRIPTION
**Pull request by targos**
Use a unique symbol instead of a string.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Thanks! 🎉

**Comment by RomainLanz** [comment]
@targos Can you reopen the PR and target `develop` branch?

**Comment by targos** [comment]
It's weird that github made me target the `main` branch by default...

**Comment by targos** [comment]
Opened https://github.com/poppinss/utils/pull/40

**Pull request merged**
