### PR TITLE
fix: allow selective exports

### LINKED ISSUE #43: Webpack | Nextjs | Import trace for requested module
### Package version

6.7.3

### Describe the bug

bug driven from usage of [flydrive-js](https://github.com/flydrive-js) in next.js

details about bug are mentioned here  [flydrive-js](https://github.com/flydrive-js/core/issues/1)

Proof  [code](https://github.com/flydrive-js/core/issues/1#issuecomment-2195936781)

### Reproduction repo

https://github.com/ahmedrowaihi/flydrive-trace-next-app

### PR DESCRIPTION
**Pull request by ahmedrowaihi**
### 🔗 Linked issue
#43 

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
improve exports 
Resolves #43 
### 📝 Checklist

- [x] I have read the [contribution guide](https://github.com/poppinss/.github/blob/main/docs/CONTRIBUTING.md).
- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by andresgutgon** [comment]
Hi, @RomainLanz what's missing here?

**Comment by thetutlage** [comment]
Hey, sorry for taking a bit too long on this PR.

I see the `emitDeclarationOnly` flag has been removed from the build script. Any specific reasons for doing that?

**Comment by ahmedrowaihi** [comment]
> Hey, sorry for taking a bit too long on this PR.
> 
> 
> 
> I see the `emitDeclarationOnly` flag has been removed from the build script. Any specific reasons for doing that?

If I remember correctly, the ts-node was not building the declarations types, since we split each file to be tree shakable with its own types, I had to remove the emitDeclarationOnl

**Comment by thetutlage** [comment]
@ahmedrowaihi The build is created using tsup (JavaScript only) and the types are created using `tsc`. May be I am missing something, but we do not use `ts-node` for generating types.

Also, being tree-shakable has been the goal of this and many other packages I maintain. I strictly create them to be used within the Node.js application

**Comment by ahmedrowaihi** [comment]
@thetutlage tbh, this PR took long a bit, I don't remember what exactly made me remove that flag..

Since you merged a fix, I will try to re-test my previous works that caused the error in first place to confirm if all went right after this PR .

**Comment by thetutlage** [comment]
@ahmedrowaihi Sure, lemme know if you face any issues 👍

**Pull request closed without merging**
